#!/usr/bin/env node
// file: to-json
let readline = require('readline')
let rl = readline.createInterface({
	input: process.stdin,
	output: process.stdout,
	terminal: false,
})

rl.on('line', function (line) {
	eval(`console.log(JSON.stringify(${line}))`)
})

